databases:
  - name: smartcommerce-db
    databaseName: smartcommerce
    user: smartcommerce
    plan: free

services:
  - type: web
    name: user-service
    runtime: docker
    dockerfilePath: ./services/user-service/Dockerfile
    dockerContext: ./services/user-service
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: smartcommerce-prod-secret-2026
      - key: DATABASE_URL
        fromDatabase:
          name: smartcommerce-db
          property: connectionString

  - type: web
    name: product-service
    runtime: docker
    dockerfilePath: ./services/product-service/Dockerfile
    dockerContext: ./services/product-service
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: smartcommerce-prod-secret-2026
      - key: DATABASE_URL
        fromDatabase:
          name: smartcommerce-db
          property: connectionString

  - type: web
    name: order-service
    runtime: docker
    dockerfilePath: ./services/order-service/Dockerfile
    dockerContext: ./services/order-service
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: smartcommerce-prod-secret-2026
      - key: DATABASE_URL
        fromDatabase:
          name: smartcommerce-db
          property: connectionString

  - type: web
    name: recommendation-service
    runtime: docker
    dockerfilePath: ./services/recommendation-service/Dockerfile
    dockerContext: ./services/recommendation-service
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: smartcommerce-prod-secret-2026
      - key: DATABASE_URL
        fromDatabase:
          name: smartcommerce-db
          property: connectionString
      - key: PRODUCT_SERVICE_URL
        value: https://product-service-be0f.onrender.com

  - type: web
    name: smartcommerce-frontend
    runtime: docker
    dockerfilePath: ./frontend/web-app/Dockerfile
    dockerContext: ./frontend/web-app
    plan: free
    dockerBuildArgs:
      - NEXT_PUBLIC_USER_SERVICE_URL=https://user-service-w1v3.onrender.com
      - NEXT_PUBLIC_PRODUCT_SERVICE_URL=https://product-service-be0f.onrender.com
      - NEXT_PUBLIC_ORDER_SERVICE_URL=https://order-service-ed7k.onrender.com
      - NEXT_PUBLIC_REC_SERVICE_URL=https://recommendation-service-3ypl.onrender.com
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dtnntuqrs
      - NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=smartcommerce
    envVars:
      - key: PORT
        value: 10000
