events { worker_connections 1024; }

http {
  server {
    listen 80;

    location /api/users {
      proxy_pass http://user-service:3001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/auth {
      proxy_pass http://user-service:3001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/products {
      proxy_pass http://product-service:3002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/orders {
      proxy_pass http://order-service:3003;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/cart {
      proxy_pass http://order-service:3003;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/recommendations {
      proxy_pass http://recommendation-service:3004;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location / {
      return 200 '{"message":"SmartCommerce Gateway running"}';
      add_header Content-Type application/json;
    }
  }
}
